"""QuantConnect LEAN bridge for exporting signals."""
from __future__ import annotations

import json
from pathlib import Path

from loguru import logger

from src.execution.signal_translator import signals_to_orders, target_weights_to_orders
from src.utils.schemas import Signal

# Re-export for convenience
__all__ = [
    "signals_to_orders",
    "target_weights_to_orders",
    "write_signals_json",
    "LEAN_ALGORITHM_TEMPLATE",
]

LEAN_ALGORITHM_TEMPLATE: str = '''
# Auto-generated QuantConnect LEAN algorithm
# Generated by QuantAgentLab lean_bridge

from AlgorithmImports import *
import json

class AIQuantStackAlgorithm(QCAlgorithm):
    """AI-powered algorithm that reads signals from JSON file."""

    def Initialize(self):
        self.SetStartDate(2023, 1, 1)
        self.SetEndDate(2024, 12, 31)
        self.SetCash(100000)
        self.signals_file = self.ObjectStore.GetFilePath("signals.json")
        self._signals = {}
        self.Schedule.On(
            self.DateRules.EveryDay(),
            self.TimeRules.AfterMarketOpen("SPY", 30),
            self.TradeOnSignals
        )

    def TradeOnSignals(self):
        """Load and act on latest signals."""
        try:
            with open(self.signals_file) as f:
                self._signals = json.load(f)
        except Exception:
            return

        for ticker, signal in self._signals.items():
            if signal["direction"] == "LONG":
                self.SetHoldings(ticker, signal["strength"] * 0.10)
            elif signal["direction"] in ("FLAT", "SHORT"):
                self.Liquidate(ticker)
'''


def write_signals_json(signals: list[Signal], path: Path) -> None:
    """Write signals to JSON file for LEAN consumption.

    The output format is::

        {ticker: {direction: str, strength: float, source: str, timestamp: str}}

    Args:
        signals: List of Signal objects to export.
        path: File path to write JSON to.  Parent directories are created if
            they do not already exist.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        s.ticker: {
            "direction": s.direction.value,
            "strength": s.strength,
            "source": s.source,
            "timestamp": s.timestamp.isoformat(),
        }
        for s in signals
    }
    path.write_text(json.dumps(data, indent=2))
    logger.debug("lean_bridge: wrote {} signal(s) to {}", len(signals), path)
